name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'google_cloud'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Export Environment Variables for Maven
        run: |
          echo "PHARMAID_DB_NAME=${{ vars.PHARMAID_DB_NAME }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_USER=${{ vars.PHARMAID_DB_USER }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_PASS=${{ vars.PHARMAID_DB_PASS }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_CLOUD_SQL_INSTANCE=${{ vars.PHARMAID_DB_CLOUD_SQL_INSTANCE }}" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: |
          echo "DB_NAME: $PHARMAID_DB_NAME"
          echo "DB_USER: $PHARMAID_DB_USER"
          echo "DB_PASS: $PHARMAID_DB_PASS"
          echo "CLOUD_SQL_INSTANCE: $PHARMAID_DB_CLOUD_SQL_INSTANCE"

      - uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'bytecoders-pharmaid-sa@bytecoders-coms4156.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/53946755718/locations/global/workloadIdentityPools/bytecoders-identity-pool/providers/github'


        #      - name: Set up Google Cloud SDK
      #        uses: google-github-actions/setup-gcloud@v1
      #        with:
      #          project_id: ${{ vars.PHARMAID_GCP_PROJECT_ID }}
      #          service_account_key: ${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}
      #
      #      - name: Save service account key to file
      #        run: |
      #          echo "${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > $GITHUB_WORKSPACE/src/main/resources/bytecoders-coms4156-key.json
      #
      #      - name: Authenticate with GCP
      #        run: gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/src/main/resources/bytecoders-coms4156-key.json

      - name: Build and Test
        run: mvn clean install

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/main'
#    environment: 'google_cloud'
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Google App Engine
#        uses: google-github-actions/deploy-appengine@v0.4.0
#        with:
#          project_id: ${{ vars.PHARMAID_GCP_PROJECT_ID }}
#          version: main
#          credentials: ${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}
#          flags: --no-cache
#          deliverables: app.yaml