name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'google_cloud'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
            
            #      - name: Set Environment Variables
            #        run: |
            #          export PHARMAID_DB_NAME="${{ vars.PHARMAID_DB_NAME }}"
            #          export PHARMAID_DB_USER="${{ vars.PHARMAID_DB_USER }}"
          #          export PHARMAID_DB_PASS="${{ vars.PHARMAID_DB_PASS }}"
          #          export PHARMAID_DB_CLOUD_SQL_INSTANCE="${{ vars.PHARMAID_DB_CLOUD_SQL_INSTANCE }}"
          #
      - name: Verify Environment Variables
        run: |
          echo "DB_NAME: ${{ vars.PHARMAID_DB_NAME }}"
          echo "DB_USER: ${{ vars.PHARMAID_DB_USER }}"
          echo "DB_PASS: ${{ vars.PHARMAID_DB_PASS }}"
          echo "CLOUD_SQL_INSTANCE: ${{ vars.PHARMAID_DB_CLOUD_SQL_INSTANCE }}"

      - uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'bytecoders-pharmaid-sa@bytecoders-coms4156.iam.gserviceaccount.com'
          workload_identity_provider: |
            projects/53946755718/locations/global/workloadIdentityPools/bytecoders-identity-pool/providers/github

      - name: Build and Test
        run: mvn clean install