name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Set up Google Cloud Credentials
        run: |
          echo "${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud-key.json
          echo "PHARMAID_GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV

      - name: Set up Database Environment Variables
        run: |
          echo "PHARMAID_DB_NAME=${{ secrets.PHARMAID_DB_NAME }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_USER=${{ secrets.PHARMAID_DB_USER }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_PASS=${{ secrets.PHARMAID_DB_PASS }}" >> $GITHUB_ENV
          echo "PHARMAID_DB_CLOUD_SQL_INSTANCE=${{ secrets.PHARMAID_DB_CLOUD_SQL_INSTANCE }}" >> $GITHUB_ENV

      - name: Build and Test
        run: mvn clean install