name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'google_cloud'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Print environment variables and secrets
        run: |
          echo "db name: ${{ vars.PHARMAID_DB_NAME }}"
          echo "db user: ${{ vars.PHARMAID_DB_USER }}"
          echo "db pass: ${{ secrets.PHARMAID_DB_PASS }}"
          echo "db cloud instance: ${{ vars.PHARMAID_DB_CLOUD_SQL_INSTANCE }}"
          echo "gcp project: ${{ vars.PHARMAID_GCP_PROJECT_ID }}"
          echo "app creds: ${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.PHARMAID_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Save service account key to file
        run: |
          echo "${{ secrets.PHARMAID_GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > $GITHUB_WORKSPACE/src/main/resources/bytecoders-coms4156-key.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/src/main/resources/bytecoders-coms4156-key.json

      - name: Build and Test
        run: mvn clean install