name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 'google_cloud'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'bytecoders-pharmaid-sa@bytecoders-coms4156.iam.gserviceaccount.com'
          workload_identity_provider: |
            projects/53946755718/locations/global/workloadIdentityPools/bytecoders-identity-pool/providers/github

      - name: Retrive GCP Secrets from Secrets Manager
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            PHARMAID_DB_NAME:bytecoders-coms4156/PHARMAID_DB_NAME
            PHARMAID_DB_USER:bytecoders-coms4156/PHARMAID_DB_USER
            PHARMAID_DB_PASS:bytecoders-coms4156/PHARMAID_DB_PASS
            PHARMAID_DB_CLOUD_SQL_INSTANCE:bytecoders-coms4156/PHARMAID_DB_CLOUD_SQL_INSTANCE

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Build and Test
        env:
          PHARMAID_DB_NAME: '${{ steps.secrets.outputs.PHARMAID_DB_NAME }}'
          PHARMAID_DB_USER: '${{ steps.secrets.outputs.PHARMAID_DB_USER }}'
          PHARMAID_DB_PASS: '${{ steps.secrets.outputs.PHARMAID_DB_PASS }}'
          PHARMAID_DB_CLOUD_SQL_INSTANCE: '${{ steps.secrets.outputs.PHARMAID_DB_CLOUD_SQL_INSTANCE }}'
        run: |
          echo "DB_INSTANCE: ${PHARMAID_DB_CLOUD_SQL_INSTANCE}"
          echo "DB_NAME: ${PHARMAID_DB_NAME}"
          echo "DB_USER: ${PHARMAID_DB_USER}"
          echo "DB_PASS: ${PHARMAID_DB_PASS}"